version: "3.9"

services:
  app:
    image: user-service:local
    container_name: us-app
    ports:
      - "10001:10001"
    depends_on:
      - postgresql
    networks:
      - us

  postgresql:
    image: postgres:14-alpine
    container_name: us-psql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=users_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./app/migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - us

networks:
  us:
